                (this.targetAowData30[0].orderNo.charAt(0) == "8" && this.targetAowData30[0].orderNo.charAt(1) == "1" && this.targetAowData30[0].orderNo.charAt(0) == "1") ||
                (this.targetAowData31[0].orderNo.charAt(0) == "8" && this.targetAowData31[0].orderNo.charAt(1) == "1" && this.targetAowData31[0].orderNo.charAt(0) == "1") ||
                (this.targetAowData32[0].orderNo.charAt(0) == "8" && this.targetAowData32[0].orderNo.charAt(1) == "1" && this.targetAowData32[0].orderNo.charAt(0) == "1") ||
                (this.targetAowData33[0].orderNo.charAt(0) == "8" && this.targetAowData33[0].orderNo.charAt(1) == "1" && this.targetAowData33[0].orderNo.charAt(0) == "1") ||
                (this.targetAowData34[0].orderNo.charAt(0) == "8" && this.targetAowData34[0].orderNo.charAt(1) == "1" && this.targetAowData34[0].orderNo.charAt(0) == "1") ||
                (this.targetAowData35[0].orderNo.charAt(0) == "8" && this.targetAowData35[0].orderNo.charAt(1) == "1" && this.targetAowData35[0].orderNo.charAt(0) == "1") ||
                (this.targetAowData36[0].orderNo.charAt(0) == "8" && this.targetAowData36[0].orderNo.charAt(1) == "1" && this.targetAowData36[0].orderNo.charAt(0) == "1") ||
                (this.targetAowData37[0].orderNo.charAt(0) == "8" && this.targetAowData37[0].orderNo.charAt(1) == "1" && this.targetAowData37[0].orderNo.charAt(0) == "1") ||
                (this.targetAowData38[0].orderNo.charAt(0) == "8" && this.targetAowData38[0].orderNo.charAt(1) == "1" && this.targetAowData38[0].orderNo.charAt(0) == "1") ||
                (this.targetAowData39[0].orderNo.charAt(0) == "8" && this.targetAowData39[0].orderNo.charAt(1) == "1" && this.targetAowData39[0].orderNo.charAt(0) == "1") ||